amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: XXXXXXXXX
  secretKey: XXXXXXXXX
  bucketName: previewappimages
  thumbnailBucketName: previewappthumbnail
server.port : 9080

