amazonProperties:
  endpointUrl: XXXXXXXXXX
  imagesBucketRegion: XXXXXXXXX
  thumbnailBucketRegion: XXXXXXXXXX
  accessKey: XXXXXXXXXX
  secretKey: XXXXXXXXXX
  bucketName: XXXXXXXXXX
  thumbnailBucketName: XXXXXXXXXX
server.port : XXXXXXXXXX
server.error.whitelabel.enabled: false
spring.http.multipart.maxFileSize : 30MB
spring.http.multipart.maxRequestSize : 30MB
