amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIAJHRZ5NLXIXACDOOQ
  secretKey: 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
  bucketName: previewappimages
  thumbnailBucketName: previewappthumbnail
server.port : 9080

